version: "3.9"
networks:
  frontend:
    driver: bridge
    name: frontend
    external: true
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    networks:
      - frontend
    volumes:
      - ./data:/data
    restart: always
    labels:
      - homepage.group=Files
      - homepage.name=Vaultwarden
      - homepage.icon=si-bitwarden
      - homepage.href=https://vaultwarden.luks.cool/
      - homepage.description=Password Manager
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.entrypoints=https
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80
    environment:
      - DOMAIN=https://vaultwarden.luks.cool/
      - SIGNUPS_ALLOWED=true
      - SIGNUPS_VERIFY=true
      - REQUIRE_DEVICE_EMAIL=false
      - INVITATIONS_ALLOWED=true
      - SHOW_PASSWORD_HINT=false
      - DISABLE_ADMIN_TOKEN=false
      - SENDS_ALLOWED=true
      - EMERGENCY_ACCESS_ALLOWED=true
      - LOG_FILE=/data/vaultwarden.log
      - LOG_LEVEL=warn
      - YUBICO_CLIENT_ID='${YUBICO_CLIENT_ID}'
      - YUBICO_SECRET_KEY='${YUBICO_SECRET_KEY}'
