version: "3"
networks:
  frontend:
    name: frontend
    external: true
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      TZ: Europe/Berlin
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
    networks:
      - frontend
    labels:
      - homepage.group=Network
      - homepage.name=PiHole
      - homepage.icon=si-pihole
      - homepage.href=https://pihole.luks.cool/admin
      - homepage.description=Recursive DNS Server
      - traefik.enable=true
      - traefik.http.routers.pihole.entrypoints=https
      - traefik.http.services.pihole.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.enable=true
