version: "3"
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # ro = read-only access to the docker.sock
      - ./config/:/etc/traefik/
    networks:
      - frontend # rename this to your custom docker network
    labels:
      homepage.group: Network
      homepage.name: Traefik
      homepage.icon: si-traefikproxy
      homepage.href: https://traefik.luks.cool/
      homepage.description: Proxy Manager
      traefik.http.routers.api.rule: Host(`traefik.luks.cool`) # Define the subdomain for the traefik dashboard.
      traefik.http.routers.api.entryPoints: https # Set the Traefik entry point.
      traefik.http.routers.api.service: api@internal # Enable Traefik API.
      traefik.enable: true # Enable Traefik reverse proxy for the Traefik dashboard.
    restart: unless-stopped
networks:
  frontend:
    # rename this to your custom docker network.
    driver: bridge
    external: true
