version: "3.3"
networks:
  frontend:
    name: frontend
    external: true
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      frontend: null
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.entrypoints=https
      - traefik.http.services.homepage.loadbalancer.server.port=3000
