version: "3"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: Europe/Berlin
      WATCHTOWER_LABEL_ENABLE: true
      WATCHTOWER_NOTIFICATION_URL: discord://wTCeAONbaW0XG3K0d8tPMquqDF7kczsi6ZfwNzOCPPelaEk6w2ic0MCxA83L8pvD27rQ@1206206159669960755
      WATCHTOWER_NOTIFICATION_TEMPLATE: '{{range .}}{{.Time.Format "2006-01-02
        15:04:05"}} ({{.Level}}): {{.Message}}{{println}}{{end}}'
      TEST: TEST
networks: {}
