version: '3.9'

networks:
  frontend:
    external: true
  backend:
    external: true

services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:2024.5.0
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      - frontend
      - backend