version: "3.5"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    networks:
      frontend: null
      backend: null
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
    #  - 1900:1900/udp #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ./config:/config
      - cache:/cache
      - /media/truenas:/media:ro
    devices:
      # VAAPI Devices
      - /dev/dri/renderD128:/dev/dri/renderD128
    labels:
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=si-jellyfin
      - homepage.href=https://jellyfin.luks.cool/
      - homepage.description=Media Streaming
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=https
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
volumes:
  cache:
networks:
  frontend:
    external: true
  backend:
    external: true
